const fs=require('fs'),path=require('path'),os=require('os');
const {spawn}=require('child_process'),{pathToFileURL}=require('url');
const profile=fs.mkdtempSync(path.join(os.tmpdir(),'portfolio-render-'));
const proc=spawn('C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{windowsHide:true,stdio:'ignore'});
const wait=ms=>new Promise(r=>setTimeout(r,ms));let ws;
(async()=>{try{
const portfile=path.join(profile,'DevToolsActivePort');for(let i=0;i<100&&!fs.existsSync(portfile);i++)await wait(100);
const port=fs.readFileSync(portfile,'utf8').split('\n')[0];const tabs=await(await fetch(`http://127.0.0.1:${port}/json`)).json();
ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});
let seq=0;const pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p[1](m.error):p[0](m.result)}};
const call=(method,params={})=>new Promise((r,j)=>{const id=++seq;pending.set(id,[r,j]);ws.send(JSON.stringify({id,method,params}))});
const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};

await call('Page.enable');
const errors=[];await call('Runtime.enable');
const original=ws.onmessage;ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.method==='Runtime.exceptionThrown')errors.push(m.params);original(e)};
await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
await call('Page.navigate',{url:pathToFileURL(path.resolve(__dirname,'../index.html')).href});await wait(700);
const movingBefore=await evaluate("document.querySelector('#field-lines path').getAttribute('d')");await wait(150);
if(movingBefore===await evaluate("document.querySelector('#field-lines path').getAttribute('d')"))throw Error('Animation not running');
await call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await wait(100);
async function shot(name,full=false){const r=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:full});fs.writeFileSync(path.join(__dirname,name+'.png'),Buffer.from(r.data,'base64'))}
await shot('desktop');
await evaluate("document.getElementById('work').scrollIntoView()");await wait(600);await shot('project');
const desktop=await evaluate(`({width:innerWidth,scroll:document.documentElement.scrollWidth,paths:document.querySelectorAll('#field-lines path').length,links:[...document.querySelectorAll('a[href]')].map(a=>a.getAttribute('href'))})`);
if(desktop.scroll>desktop.width||desktop.paths!==47)throw Error(JSON.stringify(desktop));
const details=await evaluate(`(()=>{const s=document.querySelector('summary');s.click();return s.parentElement.open})()`);if(!details)throw Error('Details did not open');
await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await evaluate("scrollTo({top:0,behavior:'instant'})");await wait(300);await shot('mobile');
const mobile=await evaluate(`({width:innerWidth,scroll:document.documentElement.scrollWidth})`);if(mobile.scroll>390)throw Error(JSON.stringify(mobile));
await evaluate("document.getElementById('work').scrollIntoView({behavior:'instant'})");await shot('mobile-project');
await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
await evaluate("document.querySelectorAll('.school').forEach(d=>d.open=false);document.getElementById('about').scrollIntoView({behavior:'instant'})");await wait(100);await shot('education-desktop');
const schools=await evaluate(`(()=>{const ds=[...document.querySelectorAll('.school')];if(ds.length!==3)throw Error('School count');for(const d of ds){d.querySelector('summary').click();if(!d.open||!d.querySelector('.course-list').textContent.trim())throw Error('Courses');}return ds.map(d=>({name:d.querySelector('strong').textContent,courses:[...d.querySelectorAll('li')].map(x=>x.textContent)}))})()`);
await shot('education-expanded');
if(!await evaluate("[...document.querySelectorAll('.school img')].every(i=>i.complete&&i.naturalWidth>0)"))throw Error('School logos');
await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
await evaluate("document.getElementById('education-title').scrollIntoView({behavior:'instant'})");await shot('education-mobile');
if(await evaluate('document.documentElement.scrollWidth')>390)throw Error('School mobile overflow');
await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
await evaluate("document.querySelectorAll('details').forEach(d=>d.open=false);document.getElementById('experience-title').scrollIntoView({behavior:'instant'})");await shot('experience-desktop');
const jobs=await evaluate(`(()=>{const ds=[...document.querySelectorAll('.experience-list .job')];if(ds.length!==4)throw Error('Experience count');for(const d of ds){d.querySelector('summary').click();if(!d.open||!d.querySelector('.job-details li'))throw Error('Experience details');}if(!ds.every(d=>d.querySelector('img').complete&&d.querySelector('img').naturalWidth>0))throw Error('Experience logos');return ds.map(d=>({role:d.querySelector('strong').textContent,dates:d.querySelector('.job-date').textContent}));})()`);
await shot('experience-expanded',true);
await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
await evaluate("document.querySelectorAll('.job').forEach(d=>d.open=false);document.getElementById('experience-title').scrollIntoView({behavior:'instant'})");await shot('experience-mobile');
await evaluate("document.querySelector('#experience-candriam summary').click()");await shot('experience-mobile-expanded');
if(await evaluate('document.documentElement.scrollWidth')>390)throw Error('Experience mobile overflow');
await evaluate("document.querySelectorAll('details').forEach(d=>d.open=false);document.getElementById('awards-title').scrollIntoView({behavior:'instant'})");await shot('awards-mobile');
if(await evaluate('document.documentElement.scrollWidth')>390)throw Error('Awards mobile overflow');
if(!await evaluate("getComputedStyle(document.querySelector('.school-date')).fontSize===getComputedStyle(document.querySelector('.job-date')).fontSize"))throw Error('Mobile dates differ');
await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
await evaluate("document.getElementById('awards-title').scrollIntoView({behavior:'instant'})");await shot('awards-desktop');
if(!await evaluate("getComputedStyle(document.querySelector('.school-date')).fontSize===getComputedStyle(document.querySelector('.job-date')).fontSize"))throw Error('Desktop dates differ');
await evaluate("document.getElementById('projects').scrollIntoView({behavior:'instant'})");await shot('research-projects-desktop');
if(!await evaluate("(()=>{const ds=[...document.querySelectorAll('.research-project-list details')];if(ds.length!==2)return false;ds.forEach(d=>d.querySelector('summary').click());return ds.every(d=>d.open&&d.querySelectorAll('li').length===3)})()"))throw Error('Project panels');
await shot('research-projects-expanded');
await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
await evaluate("document.getElementById('projects').scrollIntoView({behavior:'instant'})");await shot('research-projects-mobile');
if(await evaluate('document.documentElement.scrollWidth')>390)throw Error('Project mobile overflow');
await call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await wait(100);
await evaluate("scrollTo({top:0,behavior:'instant'})");await wait(150);
const stillBefore=await evaluate("document.querySelector('#field-lines path').getAttribute('d')");await wait(150);
if(stillBefore!==await evaluate("document.querySelector('#field-lines path').getAttribute('d')"))throw Error('Reduced motion');
if(errors.length)throw Error(JSON.stringify(errors));
const src=fs.readFileSync(path.resolve(__dirname,'../index.html'),'utf8');
for(const m of src.matchAll(/(?:src|href)="([^"#]+)"/g)){const target=m[1];if(!target.includes(':')&&!fs.existsSync(path.resolve(__dirname,'..',target)))throw Error('Missing '+target)}
fs.writeFileSync(path.join(__dirname,'qa.json'),JSON.stringify({status:'PASS',desktop,mobile,details,schools,jobs,reducedMotion:true,errors},null,2));console.log('PASS: desktop/mobile widths, local links, artwork animation, reduced motion, education and experience details.');
await call('Browser.close');
}catch(e){console.error(e);process.exitCode=1}finally{if(ws)ws.close();proc.kill()}})();
